name: Train Model with MLflow

# KAPAN WORKFLOW DIJALANKAN?
on:
  push:
    branches: [ main ]      # Setiap push ke branch main
    paths:
      - 'MLProject/**'      # Khusus jika ada perubahan di folder MLProject
  workflow_dispatch:        # Bisa juga dijalankan manual dari website GitHub

jobs:
  training:
    runs-on: ubuntu-latest  # Menggunakan server Ubuntu (gratis)
    
    steps:
      # STEP 1: Mengambil kode dari repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # STEP 2: Setup Python (versi 3.12.7 sesuai rekomendasi)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
      
      # STEP 3: Install library yang dibutuhkan
      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0
          pip install scikit-learn pandas numpy
      
      # STEP 4: Jalankan MLflow Project (training model)
      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run .
      
      # STEP 5: Upload hasil training ke GitHub (Artifact)
      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: |
            MLProject/mlruns/
          retention-days: 7
      
      # STEP 6: Selesai
      - name: Done
        run: echo "✅ Training selesai! Model tersimpan sebagai artifact"